import type { Metadata } from "next";
import "./globals.css";
import { InvoiceProvider } from "@/context/InvoiceContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <InvoiceProvider>
        <body className={`antialiased`}>{children}</body>
      </InvoiceProvider>
    </html>
  );
}
